### ISSUE TITLE
NGINX rewrite-target annotation compatibility

### ISSUE THREAD

**Issue by odaibert** [Azure/api-management-self-hosted-gateway-ingress#8]
In this example, I have an ingress controller for one service named _**order-service**_ as listed bellow.

The backend **order-service** has a **_/order_** path exposed on port 80. 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-order-service
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /order/$2
spec:
  rules:
    - host: {{.Values.dnsName}}
      http:
        paths:
          - path: /order(/|$)(.*)
            pathType: Prefix
            backend:
              service: 
                name: order-service
                port: 
                  number: 80
```

I deployed an _API Management Self Hosted Gateway Ingress_ as a ingress controller as listed bellow: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: azure-api-management/gateway
spec:
  rules:
  - http:
      paths: 
      - path: /order(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 80
```

_NGINX_ has a **rewrite-target** annotation which route the request to the **_/order_** backend service path. 

How APIM Gateway Ingress route a request to a backend service path /order? 

**_Backend service:_** http://IP/order [VERB: POST]
